nav:
  - Home: index.md
  - Lab:
      - "Learning Objectives": Intro01_overview.md
      - "Accessible to All Learners": Intro02_all_learners.md
      - "Disclaimer": Intro03_disclaimer.md
      - "Getting Started": Intro04_getting_started.md
      - "[01] SSH to devices": Task01_SSH_to_network_devices.md
      - "[02] Editing YAML": Task02_Editing_YAML_files.md
      - "[03] Global configuration": Task03_Global_configuration.md
      - "[04] Group of devices config": Task04_Group_of_devices_configuration.md
      - "[05] Single device config": Task05_Single_device_configuration.md
      - "[06] Templates 'model' (optional)": Task06_Templates_type_model.md
      - "[07] Templates 'file' (optional)": Task07_Templates_type_file.md
      - "[08] Templates 'cli' (optional)": Task08_Templates_type_cli.md
      - "[09] Schema validation": Task09_Schema_validation.md
      - "[10] Post-checks with ROBOT (optional)": Task10_Post-checks_with_ROBOT.md
      - "[11] Cleanup": Task11_Cleanup.md
      - "[12] Run CI-CD pipeline": Task12_Run_CI-CD_pipeline.md
      - "[13] Edit CI-CD (optional)": Task13_Add_Robot_testing_stage_to_CI-CD.md
      - "[14] Branch and merge request (optional)": Task14_Branch_and_merge_request.md
      - "Conclusion": Workend01_conclusion.md
      - "APPENDIX I": Task15_Appendix-I.md
  - Topologies: Intro05_topologies.md
